
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_REFRESH = 'AUTH_REFRESH';


export const ADD_USER_START = 'ADD_USER_START';
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
export const ADD_USER_FAIL = 'ADD_USER_FAIL';
export const ADD_USER_REFRESH = 'ADD_USER_REFRESH';

export const GET_BUSINESS_START = 'GET_BUSINESS_START';
export const GET_BUSINESS_SUCCESS = 'GET_BUSINESS_SUCCESS';
export const GET_BUSINESS_FAIL = 'GET_BUSINESS_FAIL';
export const GET_BUSINESS_REFRESH = 'GET_BUSINESS_REFRESH';



export const ADD_BUSINESS_START = 'ADD_BUSINESS_START';
export const ADD_BUSINESS_SUCCESS = 'ADD_BUSINESS_SUCCESS';
export const ADD_BUSINESS_FAIL = 'ADD_BUSINESS_FAIL';
export const ADD_BUSINESS_REFRESH = 'ADD_BUSINESS_REFRESH';


export const GET_DRIVERS_LOCATION_START = 'GET_DRIVERS_LOCATION_START';
export const GET_DRIVERS_LOCATION_SUCCESS = 'GET_DRIVERS_LOCATION_SUCCESS';
export const GET_DRIVERS_LOCATION_FAIL = 'GET_DRIVERS_LOCATION_FAIL';
export const GET_DRIVERS_LOCATION_REFRESH = 'GET_DRIVERS_LOCATION_REFRESH';

export const ADD_MENU_START = 'ADD_MENU_START';
export const ADD_MENU_SUCCESS = 'ADD_MENU_SUCCESS';
export const ADD_MENU_FAIL = 'ADD_MENU_FAIL';
export const ADD_MENU_REFRESH = 'ADD_MENU_REFRESH';


export const GET_MENU_START = 'GET_MENU_START';
export const GET_MENU_SUCCESS = 'GET_MENU_SUCCESS';
export const GET_MENU_FAIL = 'GET_MENU_FAIL';
export const GET_MENU_REFRESH = 'GET_MENU_REFRESH';

export const ADD_MENU_CATEGORY_START = 'ADD_MENU_CATEGORY_START';
export const ADD_MENU_CATEGORY_SUCCESS = 'ADD_MENU_CATEGORY_SUCCESS';
export const ADD_MENU_CATEGORY_FAIL = 'ADD_MENU_CATEGORY_FAIL';
export const ADD_MENU_CATEGORY_REFRESH = 'ADD_MENU_CATEGORY_REFRESH';




export const ADD_HOTEL_ROOM_START = 'ADD_HOTEL_ROOM_START';
export const ADD_HOTEL_ROOM_SUCCESS = 'ADD_HOTEL_ROOM_SUCCESS';
export const ADD_HOTEL_ROOM_FAIL = 'ADD_HOTEL_ROOM_FAIL';
export const ADD_HOTEL_ROOM_REFRESH = 'ADD_HOTEL_ROOM_REFRESH';


export const GET_HOTEL_ROOM_START = 'GET_HOTEL_ROOM_START';
export const GET_HOTEL_ROOM_SUCCESS = 'GET_HOTEL_ROOM_SUCCESS';
export const GET_HOTEL_ROOM_FAIL = 'GET_HOTEL_ROOM_FAIL';
export const GET_HOTEL_ROOM_REFRESH = 'GET_HOTEL_ROOM_REFRESH';

